/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assystem_app;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.orientechnologies.orient.core.db.ODatabasePool;
import com.orientechnologies.orient.core.db.ODatabaseSession;
import com.orientechnologies.orient.core.record.OVertex;
import java.text.SimpleDateFormat;
import java.util.Date;
public class Ajout_BDD_Frame extends javax.swing.JFrame {
    private ODatabasePool pool;
    private ODatabaseSession db;
    private Interface_app Interface_app;
    
    
    public Ajout_BDD_Frame(ODatabasePool pool, Interface_app Interface_app) {
        this.pool = pool;
        this.Interface_app=Interface_app;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipement", "Composant" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Classe");

        jLabel3.setText("Type");

        jLabel4.setText("Tension circuit puissance (V)");

        jLabel5.setText("Constructeur");

        jLabel6.setText("Tension Circuit de commande (V)");

        jButton1.setText("Ajouter à la BDD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Puissance Unitaire consommée (W)");

        jLabel8.setText("Puissance Eqt fermé");

        jLabel9.setText("Puissance Eqt ouverte");

        jLabel10.setText("Indice de confiance");

        jLabel11.setText("Origine consommation ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(jTextField3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField5)
                                            .addComponent(jTextField2))
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("Add_Classe");
        jTextField1.getAccessibleContext().setAccessibleName("Add_1");
        jTextField2.getAccessibleContext().setAccessibleName("Add_4");
        jTextField3.getAccessibleContext().setAccessibleName("Add_2");
        jTextField4.getAccessibleContext().setAccessibleName("Add_3");
        jTextField5.getAccessibleContext().setAccessibleName("Add_5");
        jTextField6.getAccessibleContext().setAccessibleName("Add_6");
        jTextField7.getAccessibleContext().setAccessibleName("Add_7");
        jTextField8.getAccessibleContext().setAccessibleName("Add_8");
        jTextField9.getAccessibleContext().setAccessibleName("Add_9");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Permet d'afficher des messages dans la JTextArea
    public void printMessage(String message) {
        SimpleDateFormat sdf = new SimpleDateFormat("HH'h'mm:ss.SSS");
        String time = sdf.format(new Date());
        String formattedMessage = time + " : " + message + "\n";
        jTextArea1.append(formattedMessage);
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength()); // Faire défiler jusqu'à la fin pour afficher le dernier message
    }
//Bouton d'ajout à la BDD
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String famille = "NULL";
        String sousFamille = "NULL";
        String type = "NULL";
        String constructeur = "NULL";
        String tension = "NULL";
        String puissanceUnitaire = "NULL";
        String puissanceTransitoire = "NULL";
        String indice = "NULL";
        String origineConsommation = "NULL";
        String TensionCircuiPuissance = "NULL";
        String TensionCircuitCommande = "NULL";
        String PuissanceUnitaireCons = "NULL";
        String PuissanceEqtFermé = "NULL";
        String PuissanceEqtOuverte = "NULL";
        String className = getTextFromAccessibleName("Add_Classe");
        if (className.equals("Composant")) {
            famille = getTextFromAccessibleName("Add_1");
            type = getTextFromAccessibleName("Add_2");
            sousFamille = getTextFromAccessibleName("Add_3");
            constructeur = getTextFromAccessibleName("Add_4");
            tension = getTextFromAccessibleName("Add_5");
            puissanceUnitaire = getTextFromAccessibleName("Add_6");
            puissanceTransitoire = getTextFromAccessibleName("Add_7");
            indice = getTextFromAccessibleName("Add_8");
            origineConsommation = getTextFromAccessibleName("Add_9");
            if (famille.isEmpty()) famille = "NULL";
            if (sousFamille.isEmpty()) sousFamille = "NULL";
            if (type.isEmpty()) type = "NULL";
            if (constructeur.isEmpty()) constructeur = "NULL";
            if (tension.isEmpty()) tension = "NULL";
            if (puissanceUnitaire.isEmpty()) puissanceUnitaire = "NULL";
            if (puissanceTransitoire.isEmpty()) puissanceTransitoire = "NULL";
            if (indice.isEmpty()) indice = "NULL";
            if (origineConsommation.isEmpty()) origineConsommation = "NULL";
            if (!tension.equals("NULL") && !isPositiveNumber(tension)) {
                printMessage("La valeur de la tension doit être un nombre strictement positif.");
                return;
            }
            if (!puissanceUnitaire.equals("NULL") && !isPositiveNumber(puissanceUnitaire)) {
                printMessage("La puissance unitaire doit être un nombre strictement positif.");
                return;
            }
            if (!puissanceTransitoire.equals("NULL") && !isPositiveNumber(puissanceTransitoire)) {
                printMessage("La puissance transitoire doit être un nombre strictement positif.");
                return;
            }
            }else if (className.equals("Equipement")) {
                type = getTextFromAccessibleName("Add_1");
                constructeur = getTextFromAccessibleName("Add_2");
                TensionCircuiPuissance = getTextFromAccessibleName("Add_3");
                TensionCircuitCommande = getTextFromAccessibleName("Add_4");
                PuissanceUnitaireCons = getTextFromAccessibleName("Add_5");
                PuissanceEqtFermé = getTextFromAccessibleName("Add_6");
                PuissanceEqtOuverte = getTextFromAccessibleName("Add_7");
                indice = getTextFromAccessibleName("Add_8");
                origineConsommation = getTextFromAccessibleName("Add_9");
                if (type.isEmpty()) type = "NULL";
                if (constructeur.isEmpty()) constructeur = "NULL";
                if (TensionCircuiPuissance.isEmpty()) TensionCircuiPuissance = "NULL";
                if (TensionCircuitCommande.isEmpty()) TensionCircuitCommande = "NULL";
                if (PuissanceUnitaireCons.isEmpty()) PuissanceUnitaireCons = "NULL";
                if (PuissanceEqtFermé.isEmpty()) PuissanceEqtFermé = "NULL";
                if (PuissanceEqtOuverte.isEmpty()) PuissanceEqtOuverte = "NULL";
                if (indice.isEmpty()) indice = "NULL";
                if (origineConsommation.isEmpty()) origineConsommation = "NULL";
                if (!TensionCircuiPuissance.equals("NULL") && !isPositiveNumber(TensionCircuiPuissance)) {
                    printMessage("La tension du circuit de puissance doit être un nombre strictement positif.");
                    return;
                }
                if (!TensionCircuitCommande.equals("NULL") && !isPositiveNumber(TensionCircuitCommande)) {
                    printMessage("La tension du circuit de commande doit être un nombre strictement positif.");
                    return;
                }
                if (!PuissanceUnitaireCons.equals("NULL") && !isPositiveNumber(PuissanceUnitaireCons)) {
                    printMessage("La puissance unitaire consommée doit être un nombre strictement positif.");
                    return;
                }
                if (!PuissanceEqtFermé.equals("NULL") && !isPositiveNumber(PuissanceEqtFermé)) {
                    printMessage("La puissance équipement fermée doit être un nombre strictement positif.");
                    return;
                }
                if (!PuissanceEqtOuverte.equals("NULL") && !isPositiveNumber(PuissanceEqtOuverte)) {
                    printMessage("La puissance équipement ouverte doit être un nombre strictement positif.");
                    return;
                }
            }

        if (!indice.equals("NULL") && !isIndiceValid(indice)) {
            printMessage("L'indice de confiance doit être un nombre entre 0 et 1.");
            return;
        }

        if (className.equals("NULL") || className.isEmpty()) {
            printMessage("Le nom de la classe est vide ou nul. Creation du vertex impossible.");
            return;
        }

        try {
            db = pool.acquire();
            printMessage("Tentative de creation du vertex pour la classe : " + className);
            OVertex v = db.newVertex(className);

            if (className.equals("Composant")) {
                v.setProperty("Famille", famille);
                v.setProperty("Type", type);
                v.setProperty("Sous Famille", sousFamille);
                v.setProperty("Constructeur", constructeur);
                v.setProperty("Tension(VCC)", tension);
                v.setProperty("Puissance Unitaire", puissanceUnitaire);
                v.setProperty("Puissance Transitoire", puissanceTransitoire);
                v.setProperty("Indice de confiance", indice);
                v.setProperty("Origine de consommation", origineConsommation);
                v.save();
                clearAllTextFields();
                printMessage("Le vertex Composant a été créé avec succès !");
            }else if (className.equals("Equipement")) {
                v.setProperty("Type", type);
                v.setProperty("Constructeur", constructeur);
                v.setProperty("Tension Circuit Puissance", TensionCircuiPuissance);
                v.setProperty("Tension Circuit de commande", TensionCircuitCommande);
                v.setProperty("Puissance Unitaire consommée", PuissanceUnitaireCons);
                v.setProperty("Puissance Eqt fermée", PuissanceEqtFermé);
                v.setProperty("Puissance Eqt ouverte", PuissanceEqtOuverte);
                v.setProperty("Indice de confiance", indice);
                v.setProperty("Origine de consommation", origineConsommation);
                v.save();
                clearAllTextFields();
                printMessage("Le vertex Equipement a été créé avec succès !");
            }

        } catch (Exception e) {
            printMessage("Erreur lors de la création du vertex : " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed
//Vérification de la valeur de la Classe pour mettre les bonnes cases à l'affichage
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedItem = (String) jComboBox1.getSelectedItem();
        if ("Equipement".equals(selectedItem)) {
            jLabel3.setText("Type");
            jLabel5.setText("Constructeur");
            jLabel4.setText("Tension circuit puissance (V)");
            jLabel6.setText("Tension Circuit de commande (V)");
            jLabel7.setText("Puissance Unitaire consommée (W)");
            jLabel8.setText("Puissance Eqt fermé");
            jLabel8.setText("Puissance Eqt ouverte");
        }
        else if ("Composant".equals(selectedItem)) {
            jLabel3.setText("Famille");
            jLabel5.setText("Type");
            jLabel4.setText("Sous Famille");
            jLabel6.setText("Constructeur");
            jLabel7.setText("Tension (VCC)");
            jLabel8.setText("Puissance Unitaire (W)");
            jLabel8.setText("Puissance Transitoire (W)");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    private boolean isPositiveNumber(String value) {
        try {
            return Double.parseDouble(value) > 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean isIndiceValid(String value) {
        try {
            double d = Double.parseDouble(value);
            return d >= 0 && d <= 1;
        } catch (NumberFormatException e) {
            return false;
        }
    }
//Accéder aux informations d'une case
    private String getTextFromAccessibleName(String accessibleName) {
        return getTextFromAccessibleNameRecursive(getContentPane(), accessibleName);
    }
    //Recherche de toutes les cases de manière récursive
    private String getTextFromAccessibleNameRecursive(java.awt.Container container, String accessibleName) {
        for (java.awt.Component comp : container.getComponents()) {
            if (comp instanceof javax.swing.JTextField) {
                javax.swing.JTextField textField = (javax.swing.JTextField) comp;
                if (accessibleName.equals(textField.getAccessibleContext().getAccessibleName())) {
                    return textField.getText();
                }
            }    
            else if (comp instanceof javax.swing.JComboBox) {
                javax.swing.JComboBox<?> comboBox = (javax.swing.JComboBox<?>) comp;
                if (accessibleName.equals(comboBox.getAccessibleContext().getAccessibleName())) {
                    Object selectedItem = comboBox.getSelectedItem();
                    return selectedItem != null ? selectedItem.toString() : "";
                }
            }
            else if (comp instanceof java.awt.Container) {
                String result = getTextFromAccessibleNameRecursive((java.awt.Container) comp, accessibleName);
                if (!result.isEmpty()) {
                    return result;
                }
            }
        }
        return "";
    }
    //Vider les cases après un ajout
    private void clearAllTextFields() {
        clearAllTextFieldsRecursive(getContentPane());
    }
    //Vider toutes les cases de manière récursive
    private void clearAllTextFieldsRecursive(java.awt.Container container) {
        for (java.awt.Component comp : container.getComponents()) {
            if (comp instanceof javax.swing.JTextField) {
                javax.swing.JTextField textField = (javax.swing.JTextField) comp;
                textField.setText("");
            }
            else if (comp instanceof java.awt.Container) {
                clearAllTextFieldsRecursive((java.awt.Container) comp);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
